# Utilisez l'image de base Nginx
FROM nginx:alpine

# Supprimez le fichier de configuration par défaut de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiez votre propre fichier de configuration personnalisé
COPY nginx.conf /etc/nginx/conf.d

# Copiez les images statiques dans le répertoire de contenu de Nginx
COPY static-images /usr/share/nginx/html/images

# Exposez le port 80 pour le trafic HTTP
EXPOSE 8070

# Démarrez Nginx lors du démarrage du conteneur
CMD ["nginx", "-g", "daemon off;"]